- .github/workflows/deploy.yml
- build.gradle
- docker-compose.yml
- **간략한 설명**:
:  docker compose MySQL 환경변수 설정 수정 및 deploy.yml에 배포 스크립트 명령어 수정
---
- docker compose 설정이 변경되어 로컬에서 재실행 해야 합니다. 
- 재실행 하시기전 루트의 database 디렉토리 하위에 data 디렉토리를 삭제 후 재실행 시켜주세요!
---
- **이슈 링크** : #24 
This close #24
> [fix] cd 서버에 배포하는 스크립트 수정

- .gitignore
- build.gradle
- src/main/java/com/haejwo/tripcometrue/domain/member/controller/MemberController.java
- src/main/java/com/haejwo/tripcometrue/domain/member/dto/request/LoginRequestDto.java
- src/main/java/com/haejwo/tripcometrue/domain/member/dto/request/SignUpRequestDto.java
- src/main/java/com/haejwo/tripcometrue/domain/member/dto/response/LoginResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/member/dto/response/SignUpResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/member/dto/response/TestUserResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/member/entity/Member.java
- src/main/java/com/haejwo/tripcometrue/domain/member/service/MemberService.java
- src/main/java/com/haejwo/tripcometrue/global/config/AppConfig.java
- src/main/java/com/haejwo/tripcometrue/global/exception/GlobalExceptionRestAdvice.java
- src/main/java/com/haejwo/tripcometrue/global/jwt/JwtAuthenticationFilter.java
- src/main/java/com/haejwo/tripcometrue/global/jwt/JwtAuthorizationFilter.java
- src/main/java/com/haejwo/tripcometrue/global/jwt/JwtKey.java
- src/main/java/com/haejwo/tripcometrue/global/jwt/JwtProperties.java
- src/main/java/com/haejwo/tripcometrue/global/jwt/JwtProvider.java
- src/main/java/com/haejwo/tripcometrue/global/jwt/SigningKeyResolver.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/ApplicationAuditAware.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/AuthConfig.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/PrincipalDetails.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/SpringSecurityConfig.java
- src/test/http/member/login.http
- src/test/http/member/signup.http
- src/test/http/member/testjwt.http
- **간략한 설명**:
- 로그인 인가 권한이 필요한 경우 MemberController 에 구현된 test 메서드를 참고하여 코드를 구현하면 됨
- 로그인 인가 권한이 필요한 api를 이용할 경우 아래처럼 header에 토큰을 넣으면 됨
- 아래 코드는 test폴더 하위 http 폴더 내에서 확인 가능
---
- **security jwt 를 이용한 로그인 및 회원가입 기능 추가**
- discussion에서 제안한대로 dto 클래스 이름 변경 및 entity id 값 변경 
---
- **이슈 링크1** : #3
> [feat] security jwt 를 이용한 로그인 및 회원가입 기능 추가

- src/main/java/com/haejwo/tripcometrue/domain/member/controller/MemberController.java
- src/main/java/com/haejwo/tripcometrue/domain/member/entity/Member.java
- src/main/java/com/haejwo/tripcometrue/domain/member/repository/MemberRepository.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/GoogleUserInfo.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/KakaoUserInfo.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/NaverUserInfo.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/OAuth2LoginSuccessHandler.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/OAuth2UserInfo.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/PrincipalOauth2UserService.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/SpringSecurityConfig.java
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/test/http/member/login.http
- src/test/resources/application.yml
---
- oauth2 로그인 기능(구글,네이버,카카오)가 추가 되었습니다.
---
- **이슈 링크2** : #3
---
> [feat] oauth2 로그인 기능 추가 (구글,네이버,카카오)

- src/main/java/com/haejwo/tripcometrue/domain/place/controller/PlaceController.java
- src/main/java/com/haejwo/tripcometrue/domain/place/dto/request/PlaceFilterRequestDto.java
- src/main/java/com/haejwo/tripcometrue/domain/place/dto/request/PlaceRequestDto.java
- src/main/java/com/haejwo/tripcometrue/domain/place/dto/response/PlaceResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/place/entity/Place.java
- src/main/java/com/haejwo/tripcometrue/domain/place/service/PlaceService.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/controller/TripRecordController.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/request/TripRecordRequestDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/response/TripRecordResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/ExpenseRangeType.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/ExpenseType.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecord.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordSchedule.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/TripRecordRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/service/TripRecordService.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/SpringSecurityConfig.java
- **간략한 설명**:
: 여행후기(trip_record)에 대한 기본 CRUD 구현, 여행후기스케쥴(trip_record_schedule) 엔티티 구현
---
-  여행후기(trip_record) 엔티티 구현
- 여행후기스케쥴(trip_record_schedule) 엔티티 구현
---
- **이슈 링크1** : #34 
---
- **주목할 사항** 
- 현재없음
- 
---
- **관련 문서 링크** 
- 현재없음
- 
---
- (테스트계획)
- (테스트결과)
---
- **참조 링크**
- 현재없음
- **참고 자료**
- 현재없음
> [feat] 여행후기 기본 구현 완료

- src/main/java/com/haejwo/tripcometrue/domain/city/controller/CityController.java
- src/main/java/com/haejwo/tripcometrue/domain/city/dto/request/AddCityRequestDto.java
- src/main/java/com/haejwo/tripcometrue/domain/city/dto/response/CityResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/city/entity/City.java
- src/main/java/com/haejwo/tripcometrue/domain/city/exception/CityNotFoundException.java
- src/main/java/com/haejwo/tripcometrue/domain/city/repository/CityRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/city/service/CityService.java
- src/main/java/com/haejwo/tripcometrue/global/enums/Continent.java
- src/main/java/com/haejwo/tripcometrue/global/enums/Country.java
- src/main/java/com/haejwo/tripcometrue/global/exception/ErrorCode.java
- **간략한 설명**:
: 도시 도메인의 엔티티를 생성하고 도시 생성/단일 조회/삭제 기능을 구현합니다.
---
- ### 주요작성
- 도시 엔티티 추가
- 도시 레포지토리 추가
- 도시 서비스 추가
- 도시 컨트롤러 추가
---
- **이슈 링크** : #27 
---
- **주목할 사항** 
- global 패키지 하위 enums 패키지를 생성해 공통적으로 사용될 Enum 클래스를 추가했습니다.
- Country 
- Continent
---
- 추후 서비스/컨트롤러 테스트 작성 예정
---
This close #27
> [feat] 도시 도메인 엔티티 및 기본 crud 로직 구현

- src/main/java/com/haejwo/tripcometrue/domain/triprecord/controller/TripRecordController.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/TripRecordScheduleDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/response/member/TripRecordMemberResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/response/triprecord_schedule/TripRecordScheduleDetailResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecord.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordImage.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordSchedule.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordViewCount.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/TripRecordViewCountRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/service/TripRecordService.java
- **간략한 설명**:
: 여행 후기 상세조회 페이지에 대한 1차 구현이 완료되었다. 현재 당장 필요하다고 생각되는 정보는 모두 응답으로 출력되는것으로 확인된다.
---
- schedule 엔티티 스프링 내에서 place 과의 관계를 매핑하지 않고 암시적 관계로서 place_id만 가지고 있는 것으로 수정
- 여행 후기 상세조회 시, 해당 여행후기 정보(이미지, 태그 포함)과 관련 스케쥴을 한번에 보내 주도록 구현
---
- **이슈 링크1** : #53 
---
- **주목할 사항** 
- schedule 엔티티 place 매핑관계 해제
- 
---
- **관련 문서 링크** 
- (링크1)
- 
---
- (테스트계획)
- (테스트결과)
---
- **참조 링크**
- (링크1)
- **참고 자료**
- (자료1)
> [feat] 여행후기 상세조회 페이지 1차 구현 완료

- src/main/java/com/haejwo/tripcometrue/domain/tripplan/controller/TripPlanController.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/controller/TripPlanControllerAdvice.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/dto/request/TripPlanScheduleRequestDto.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/dto/response/CopyTripPlanFromTripRecordResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/dto/response/TripPlanDetailsResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/dto/response/TripPlanScheduleResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/entity/TripPlan.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/entity/TripPlanSchedule.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/exception/TripPlanNotFoundException.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/repository/TripPlanScheduleRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/sevice/TripPlanService.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/controller/TripRecordController.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/controller/TripRecordEditController.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/controller/TripRecordEditControllerAdvice.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/request/CreateSchedulePlaceRequestDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/request/TripRecordScheduleRequestDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecord.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordSchedule.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordStore.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord_image/TripRecordImageRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord_schedule/TripRecordScheduleRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord_store/TripRecordStoreRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord_tag/TripRecordTagRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/service/TripRecordEditService.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/service/TripRecordService.java
- src/main/java/com/haejwo/tripcometrue/global/exception/ErrorCode.java
- src/main/java/com/haejwo/tripcometrue/global/exception/PermissionDeniedException.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/SpringSecurityConfig.java
- src/test/http/trip_plan/trip_plan.http
- src/test/http/trip_record/trip_record_edit.http
- **간략한 설명**:
- 여행 계획 수정 및 삭제 api를 추가하였습니다.
- 여행 후기 수정 및 삭제 api를 추가하였습니다.
- 여행 후기를 나의 여행 계획으로 복사해 오는 api를 추가하였습니다.
- 여행계획을 tripPlanId로 상세조회 하는 api를 추가 하였습니다.
- 불필요한 연관관계를 삭제하였습니다.
---
- TripRecord 수정 api 추가 
- TripRecordSchedule에 member 연관관계 삭제 
- TripPlan 삭제 코드 추가 
- TripPlan 수정 api 추가 
- TripPlanSchedule에 member 연관관계 삭제 
- 여행 계획 작성시 장소에 대한 검증 로직 추가 
- 여행 후기 작성시 장소에 대한 검증 로직 추가 
- 여행 후기를 복사해서 여행 계획 생성하는 api 추가 
- tripRecord와 tripRecordStore 연관관계 추가
---
- **이슈 링크1** : #54
> [feat] 여행 계획,후기 수정및 삭제 관련 api 추가 및 여행후기를 여행계획으로 복사해 오는 api 추가

- src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordViewHistory.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/service/TripRecordService.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecordViewHistory/controller/TripRecordViewHistoryController.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecordViewHistory/controller/TripRecordViewHistoryControllerAdvice.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecordViewHistory/dto/request/TripRecordViewHistoryRequestDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecordViewHistory/dto/response/TripRecordViewHistoryResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecordViewHistory/repository/TripRecordViewHistoryRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecordViewHistory/service/TripRecordViewHistoryService.java
- src/test/http/trip_record/view_history.http
- **간략한 설명**:
: 마이페이지 내부 최근에 본 후기 기능 구현
---
- TripRecordViewHistory 도메인 작성
- TripRecord 조회 마다 trip_record_view_history 테이블에 member_id, trip_record_id 등록 메서드(addViewHistory) 구현
- 기존에 보았던 데이터 처리 -> basetimeEntity의 UpdatedAt 필드값만 수정 후 재저장
- 등록된 데이터 조회 요청 시 UpdatedAt 기준 내림차순 페이지 응답데이터로 전송
---
- **이슈 링크1** : #38 
---
- **주목할 사항** 
- TripRecordViewHistory 엔티티의 소속 패키지가 일단 triprecord 패키지에 있음
- TripRecordService 수정은 addViewHistory 추가 및 관련 의존성 주입 외에 없음
- 추후 예외처리 추가 필요
> [feat] 마이페이지/ 최근에 본 후기 기능 1차 구현

- src/main/java/com/haejwo/tripcometrue/domain/city/controller/CityContentReadController.java
- src/main/java/com/haejwo/tripcometrue/domain/city/dto/response/TopCityResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/city/entity/City.java
- src/main/java/com/haejwo/tripcometrue/domain/city/repository/CityRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/city/repository/CityRepositoryCustom.java
- src/main/java/com/haejwo/tripcometrue/domain/city/repository/CityRepositoryImpl.java
- src/main/java/com/haejwo/tripcometrue/domain/city/service/CityContentReadService.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/controller/TripRecordController.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/controller/TripRecordScheduleVideoController.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/query/NewestTripRecordScheduleVideoQueryDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/response/triprecord/TopTripRecordResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/response/triprecord_schedule_media/NewestTripRecordScheduleVideoResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordScheduleVideo.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord/TripRecordCustomRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord/TripRecordCustomRepositoryImpl.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord_schedule_video/TripRecordScheduleVideoRepositoryCustom.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord_schedule_video/TripRecordScheduleVideoRepositoryImpl.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/service/TripRecordScheduleVideoService.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/service/TripRecordService.java
- src/main/java/com/haejwo/tripcometrue/global/validator/HomeTopListQueryTypeValidator.java
- src/main/java/com/haejwo/tripcometrue/global/validator/HomeVideoListQueryTypeValidator.java
- src/main/java/com/haejwo/tripcometrue/global/validator/annotation/HomeTopListQueryType.java
- src/main/java/com/haejwo/tripcometrue/global/validator/annotation/HomeVideoListQueryType.java
- src/test/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord_schedule_image/TripRecordScheduleImageRepositoryTest.java
- src/test/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord_schedule_video/TripRecordScheduleVideoRepositoryTest.java
- **간략한 설명**:
:  홈 메인 피드 API를 1차 구현 완료했습니다.
---
- 홈 메인 최신 등록 쇼츠 리스트 조회 API
- 홈 메인 인기 도시 리스트 조회 API
- 홈 메인 인기 여행 후기 리스트 조회 API
- 홈 메인 크리에이터 리스트 조회 API : 미구현 -> 추후 구현 예정입니다!
- ### 🌟 변경사항
- TripRecordScheduleVideo 엔티티에 'thumbnailUrl' 필드를 추가했습니다.
- 쇼츠 리스트 GET 요청시 썸네일 url을 보내줘야 한다는 프론트 측의 요청에 따라 추가했습니다.
- City 엔티티에 'storeCount', 'imageUrl' 필드 추가
- 'storeCount' : 도시 보관수
- 'imageUrl' : 도시 대표 이미지
---
- **이슈 링크** : #80 
---
- TripRecordScheduleVideoRepository에 구현한 전체/국내/해외 최신 등록 쇼츠 리스트 조회 테스트 코드를 작성했습니다.
- 정상 동작 확인 완료했습니다.
This close #80
> [feat] 홈 메인 피드 API 1차 구현

- src/main/java/com/haejwo/tripcometrue/domain/city/repository/CityRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/controller/TripRecordEditController.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/response/triprecord/GetCountryCityResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/response/triprecord/GetCountryResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/service/TripRecordEditService.java
- src/main/java/com/haejwo/tripcometrue/global/enums/Country.java
- src/main/java/com/haejwo/tripcometrue/global/springsecurity/SpringSecurityConfig.java
- src/test/http/trip_record/trip_record_edit.http
- **간략한 설명**:
:  계획,후기 작성 시 DB에 있는 국가-도시를 조회할 수 있는 api를 추가하였습니다. 
---
- 계획,후기 작성 시 DB에 있는 국가-도시를 조회할 수 있는 api를 추가
- country테이블을 따로 생성하지 않았으므로 country 대표이미지들을 country enum에서 관리하도록 추가
---
- **이슈 링크1** : #85
> [feat] 계획,후기 작성시 국가-도시 조회 기능 추가

- src/main/java/com/haejwo/tripcometrue/domain/review/placereview/controller/PlaceReviewController.java
- src/main/java/com/haejwo/tripcometrue/domain/review/placereview/dto/response/PlaceReviewListResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/review/placereview/entity/PlaceReview.java
- src/main/java/com/haejwo/tripcometrue/domain/review/placereview/repository/PlaceReviewRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/review/placereview/service/PlaceReviewService.java
- src/main/java/com/haejwo/tripcometrue/domain/review/triprecordreview/service/TripRecordReviewService.java
- **간략한 설명**:
: 여행지 리뷰 기능 추가 및 리팩토링을 진행했습니다.
---
- 프론트엔드와 논의한 결과, 여행지 리뷰가 일부 성공하더라도 정책적으로 `200` 코드를 반환하기로 합의했습니다.
- controller 계층 코드가 훨씬 깔끔해졌습니다.
- 기존 버전은 `Page 인터페이스`를 그대로 반환했기 때문에 불필요한 정보까지 전달했습니다.
- Page 인터페이스에서 중요한 정보만 추출해서 `PlaceReviewListResponseDto` 로 반환합니다.
- `Long totalCount`  :  조회한 총 개수
- `int nowPageNumber`  :  현재 페이지 넘버
- `boolean isFirst`  :  현재 페이지가 처음인지 여부
- `boolean isLast`  :  현재 페이지가 마지막인지 여부
- `List<PlaceReviewResponseDto> placeReviews`  :  PlaceReview 리스트
- 여행지 리뷰를 등록할 때 이미지를 등록하지 않았다가, 수정 API를 통해 처음 이미지를 등록할 시 포인트 +1점 적립합니다.
- 만약 수정 API에서 이미지를 삭제해 `null`로 만든 후, 다시 이미지를 등록하면 부정 적립으로 판단하고 포인트를 적립하지 않습니다.
- 만약 로그인한 사용자가 작성하지 않은 리뷰를 수정하려고 할 시 `UserInvalidAccessException` 예외가 발생합니다.
---
- **이슈 링크1** : #95
> [refactor] 여행지 리뷰(PlaceReview) 기능 추가 및 리팩토링

- src/main/java/com/haejwo/tripcometrue/domain/member/service/MemberService.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/controller/TripPlanController.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/dto/request/TripPlanRequestDto.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/sevice/TripPlanService.java
- src/test/http/trip_plan/trip_plan.http
- **간략한 설명**:
: 여행 후기를 여행 계획으로 복사해 오는 로직 수정, 여행 계획 작성 시 body값 수정, generateName 함수 수정
---
- 여행 후기에서 여행 계획 조회하는 api http 메소드 변경 
- 후기 복사시 trip_record_store에 생성되는 로직 삭제 
- 여행계획 생성시 참조한 후기 id 입력할 수 있도록 body 추가 
- generateName 함수 수정 
---
- **이슈 링크1** : #106
> [fix] 여행 후기를 여행 계획으로 복사해 오는 로직 수정, 여행 계획 작성 시 body값 수정, generateName 함수 수정

- src/main/java/com/haejwo/tripcometrue/domain/place/controller/PlaceController.java
- src/main/java/com/haejwo/tripcometrue/domain/place/dto/response/PlaceNearbyResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/place/dto/response/PlaceResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/place/entity/Place.java
- src/main/java/com/haejwo/tripcometrue/domain/place/repositroy/PlaceCustomRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/place/repositroy/PlaceCustomRepositoryImpl.java
- src/main/java/com/haejwo/tripcometrue/domain/place/service/PlaceService.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/response/triprecord/TripRecordListResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord/TripRecordCustomRepositoryImpl.java
- **간략한 설명**:
: 특정 여행지 근처(좌표기준) 여행지 5개 리스트 응답
---
- 여행지 엔티티에 전화번호 추가
- 근처추천여행지 기능 추가
- 여행후기 리스트 응답 데이터에 평점 추가
---
- **이슈 링크1** : #101 
---
- **주목할 사항** 
- (특이사항1)
- 
---
- **관련 문서 링크** 
- (링크1)
- 
---
- (테스트계획)
- (테스트결과)
---
- **참조 링크**
- (링크1)
- **참고 자료**
- (자료1)
> [feat] 여행지 근처추천여행지 기능 구현

- src/main/java/com/haejwo/tripcometrue/domain/comment/placereview/controller/PlaceReviewCommentController.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/placereview/controller/PlaceReviewCommentControllerAdvice.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/placereview/dto/request/PlaceReviewCommentRequestDto.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/placereview/dto/response/PlaceReviewCommentListResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/placereview/dto/response/PlaceReviewCommentResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/placereview/entity/PlaceReviewComment.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/placereview/exception/PlaceReviewCommentNotFoundException.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/placereview/repository/PlaceReviewCommentRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/placereview/service/PlaceReviewCommentService.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/controller/TripRecordCommentController.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/dto/request/TripRecordCommentRequestDto.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/dto/response/TripRecordCommentResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/entity/TripRecordComment.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/service/TripRecordCommentService.java
- src/main/java/com/haejwo/tripcometrue/domain/review/placereview/controller/PlaceReviewController.java
- src/main/java/com/haejwo/tripcometrue/domain/review/placereview/dto/response/PlaceReviewListResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/review/placereview/dto/response/PlaceReviewResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/review/placereview/entity/PlaceReview.java
- src/main/java/com/haejwo/tripcometrue/domain/review/placereview/service/PlaceReviewService.java
- src/main/java/com/haejwo/tripcometrue/domain/review/triprecordreview/entity/TripRecordReview.java
- src/main/java/com/haejwo/tripcometrue/domain/review/triprecordreview/repository/TripRecordReviewRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/review/triprecordreview/service/TripRecordReviewService.java
- src/main/java/com/haejwo/tripcometrue/global/exception/ErrorCode.java
- **간략한 설명**:
: 여행지 리뷰 댓글, 대댓글에 대한 CURD 기능을 구현했습니다.
---
- 여행지 리뷰 id를 가지고 댓글을 등록합니다.
- 특정 댓글 id를 가지고 대댓글을 등록합니다.
- 정책상 부모 댓글을 삭제하면 자식 댓글(대댓글)도 전부 삭제됩니다.
- 여행지 리뷰 댓글, 대댓글은 따로 조회가 불가능합니다.
- 특정 `여행지 리뷰`(PlaceReview)를 조회하면 댓글도 함께 조회됩니다.
```json
{
"code": 200,
"data": {
"placeReviewId": 89,
"memberId": 1,
"nickname": "열받은너구리",
"profileUrl": "https://tripcometrue-dev-s3-bucket.s3.ap-northeast-2.amazonaws.com/e3df3aed-95d1-4079-850e-3aac8d1dd4d5_Screen%20Shot%202023-12-22%20at%2011.52.41%20AM.png",
"imageUrl": "https://tripcometrue-dev-s3-bucket.s3.ap-northeast-2.amazonaws.com/c75ca5b1-141d-4ca3-8e65-1253453dd30c.png",
"content": "평야 양떼목장 양양 여자 섬 오렌지 흐림 산 오렌지",
"likeCount": 0,
"createdAt": "2024-01-15T00-01-57",
"amILike": false
"commentCount": 4,
"comments": [
{
"commentId": 31,
"memberId": 6, …
```
> [feat] 여행지 리뷰 댓글, 대댓글(PlaceReviewComment) CRUD 기능 구현

- src/main/java/com/haejwo/tripcometrue/domain/place/controller/PlaceController.java
- src/main/java/com/haejwo/tripcometrue/domain/place/dto/response/PlaceResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/place/service/PlaceService.java
- src/main/java/com/haejwo/tripcometrue/domain/store/repository/PlaceStoreRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/store/repository/TripRecordStoreRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/response/triprecord/TripRecordDetailResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/response/triprecord_schedule_media/TripRecordScheduleImageListResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/service/TripRecordService.java
- **간략한 설명**:
: 여행후기, 여행지 상세페이지 응답 사용자 보관유무 추가
---
- 여행후기 상세페이지 응답 사용자 보관유무 추가
- 여행지 상세페이지 응답 사용자 보관유무 추가
- 여행지 상세 페이지의 여행갤러리 응답데이터 수정 
---
- **이슈 링크1** : #112 
---
- **주목할 사항** 
- (특이사항1)
- 
---
- **관련 문서 링크** 
- (링크1)
- 
---
- (테스트계획)
- (테스트결과)
---
- **참조 링크**
- (링크1)
- **참고 자료**
- (자료1)
> [feat] 여행후기, 여행지 상세페이지 응답 사용자 보관유무 추가

- src/main/java/com/haejwo/tripcometrue/domain/likes/controller/LikesController.java
- src/main/java/com/haejwo/tripcometrue/domain/likes/service/LikesService.java
- src/main/java/com/haejwo/tripcometrue/domain/member/controller/MemberController.java
- src/main/java/com/haejwo/tripcometrue/domain/member/entity/Member.java
- src/main/java/com/haejwo/tripcometrue/domain/member/exception/NicknameChangeNotAvailableException.java
- src/main/java/com/haejwo/tripcometrue/domain/member/service/MemberService.java
- src/main/java/com/haejwo/tripcometrue/domain/review/placereview/exception/PlaceReviewNotFoundException.java
- src/main/java/com/haejwo/tripcometrue/global/exception/ErrorCode.java
- src/test/http/likes/likes.http
- **간략한 설명**:
: 닉네임 변경에 기한 설정 및 api응답값들 조정 필요한 부분 수정
---
- 닉네임 변경기한(6개월) 설정
- 좋아요 API URL 수정
- 에러메세지 수정 필요부분 수정
---
- **이슈 링크1** : #104 
---
> [refactor] 닉네임 변경기한 설정 및 일부 API 응답값 조정

- src/main/java/com/haejwo/tripcometrue/domain/city/controller/CityInfoReadController.java
- src/main/java/com/haejwo/tripcometrue/domain/city/service/CityInfoReadService.java
- **간략한 설명**:
: 프론트 요청에 따른 도시 상세 환율 정보 조회 API 변경 및 로직 수정
---
- ### **변경사항**
- 기존 : '/v1/cities/exchange-rates?curUnit={curUnit}'
- 도시의 환율 단위를 RequestParam으로 요청값으로 받아 환율 정보 조회
- 변경 후 : '/v1/cities/{cityId}/exchange-rates'
- 도시 식별자를 요청값으로 받아 도시 엔티티로부터 환율 단위를 추출해 환율 정보 조회
---
- **이슈 링크** : #119 
---
This close #119
> [refactor] 도시 상세 환율 정보 조회 API 변경 및 로직 리팩토링 수정

- src/main/java/com/haejwo/tripcometrue/domain/review/triprecordreview/dto/response/latest/EmptyTripRecordReviewResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/review/triprecordreview/dto/response/latest/LatestTripRecordReviewResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/review/triprecordreview/repository/TripRecordReviewRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/review/triprecordreview/service/TripRecordReviewService.java
- src/main/java/com/haejwo/tripcometrue/domain/tripplan/repository/TripPlanRepository.java
- **간략한 설명**:
- 여행 후기 리뷰에서 본문을 작성할 수 있는지 여부를 검증하고 반환하는 기능을 구현했습니다.
- `canRegisterContent` 값으로 작성 가능 여부를 반환합니다.
- 로그인한 사용자가 등록한 `여행 후기 별점 id`를 반환합니다.
---
- 작성 여부는 몇 가지 기준으로 판단합니다.
---
- **이슈 링크1** : #8
> [feat] 여행 후기 리뷰(TripRecordReview)의 본문(content) 작성 가능 여부 검증 로직 구현

- src/main/java/com/haejwo/tripcometrue/domain/city/controller/CityContentReadController.java
- src/main/java/com/haejwo/tripcometrue/domain/city/service/CityContentReadService.java
- src/main/java/com/haejwo/tripcometrue/domain/place/repositroy/PlaceCustomRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/place/repositroy/PlaceCustomRepositoryImpl.java
- src/main/java/com/haejwo/tripcometrue/domain/place/service/PlaceService.java
- src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord/TripRecordCustomRepositoryImpl.java
- src/test/java/com/haejwo/tripcometrue/domain/place/repositroy/PlaceRepositoryTest.java
- **간략한 설명**:
: 도시 상세 피드 여행지 검색 조회 API 구현
---
- ### **(주요작성/변경사항)**
- 기존 도시 여행 전체 페이징 조회 API에 여행지명 검색 기능 추가 
-  '/v1/cities/{cityId}/places/list?placeName={placeName}'
- Querydsl OrderSpecifier 'order by null' 정렬 기준 추가
---
- **이슈 링크** : #122 
---
This close #122
> 도시 상세 피드 여행지 검색 조회 API 구현

- src/main/java/com/haejwo/tripcometrue/domain/alarm/controller/AlarmController.java
- src/main/java/com/haejwo/tripcometrue/domain/alarm/dto/response/AlarmResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/alarm/entity/Alarm.java
- src/main/java/com/haejwo/tripcometrue/domain/alarm/entity/AlarmType.java
- src/main/java/com/haejwo/tripcometrue/domain/alarm/repository/AlarmRepository.java
- src/main/java/com/haejwo/tripcometrue/domain/alarm/service/AlarmService.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/placereview/service/PlaceReviewCommentService.java
- src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/service/TripRecordCommentService.java
- src/main/java/com/haejwo/tripcometrue/domain/review/triprecordreview/service/TripRecordReviewService.java
- **간략한 설명**:
:  댓글/리뷰 작성에 대한 마이페이지 내부 알림 보관 리스트 기능 구현
---
- 알림 테이블 생성 후 , 알림 트리거(여행후기 댓글, 여행지리뷰 댓글, 여행후기 리뷰) 상황 발생시 알림 데이터 저장
- 알림 트리거 상황에 따라 alarmType필드는 ENUM 활용하여 다르게 저장
- objectId(트리거 발생 대상객체id) 나 windowId(트리거 발생 대상객체가 포함된 위치 id) 는 도메인 구별없이 숫자로 응답값에 포함됨. 프론트 라우팅 보조용도로 사용
- alarmArgs 변수에 커스텀 메시지(댓글/리뷰 작성자)를 넣어서 반환
---
- **이슈 링크1** : #68 
---
- **주목할 사항** 
- 이후 여행후기 리뷰 작성 조건 충족시 리뷰작성요청에 대한 알림 케이스 구현 필요
- 알림기능 구현에 대한 다른 효과적인 방법이나 기술스택 검토 
---
> [feat] 마이페이지 알림 보관 리스트 기능 구현

- src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/service/TripRecordCommentService.java
- **간략한 설명**:
: 로그인하지 않은 유저도 여행 후기 댓글을 조회할 수 있도록 수정했습니다.
---
- 로그인하지 않으면 PrincipalDetails가 null로 들어옵니다. null 값을 이용해 memberRepository에서 멤버를 찾는 과정에서 에러가 발생했기 때문에, if문을 통해 로그인 하지 않은 유저가 통과될 수 있도록 수정했습니다.
```java
private Member getMember(PrincipalDetails principalDetails) {
if (principalDetails != null) {
return memberRepository.findById(principalDetails.getMember().getId())
.orElseThrow(UserNotFoundException::new);
}
return null;
}
```
---
- **이슈 링크1** : #9
> [fix] 로그인하지 않은 사용자도 여행 후기 댓글(TripRecordComment) 목록 조회 가능하도록 수정

- src/main/java/com/haejwo/tripcometrue/domain/store/dto/response/CityStoreResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/store/dto/response/PlaceStoreResponseDto.java
- src/main/java/com/haejwo/tripcometrue/domain/store/dto/response/TripRecordStoreResponseDto.java
- **간략한 설명**:
: Store Dto 필드값 불필요 항목 삭제 및 필요 항목 추가
---
- Store Dto 필드값 불필요 항목 삭제 및 필요 여지 항목 추가
---
- **이슈 링크1** : #103 
---
> [fix] store Response Dto 필드값 정리
